token = "THE TOKEN SELIVERED BY DISCORD TO ALLOW YOU TO HAVE A DISCORD BOT"
your_discord_account_id = "THE ID TAHT BELONGS TO YOUR DISOCRD ACCOUNT"
account_available_in_gen = ['spotify','tidal', 'nord', 'crunchyroll', 'hulu','disney','funimation','hbomax','wwe','pornhub']
website_link = "YOUR WEBSITE LINK TO THE GENERATOR LANDING PAGE"


""""
YOU CAN GET A TOKEN IN THEIR DEVELOPER SITE (YOU NEED AN DISCORD ACCOUNT TO APPLY) https://discord.com/developers/applications

WE NEED THE DISCORD ACCOUNT ID BECAUSE SO YOU CAN PREVENT OTHER USERS TO USE SOME COMMANDS THAT CAN POTENTIALLY ERASE EVERYTHING IN THE DB

THE LIST OF ACCOUNT ARE WHAT YOU SHOW AS AVAILABLE IN YOUR DISCORD SERVER WHERE YOU HAVE THE DISCORD BOT, THE ONE LEFT THERE ARE THE ONE I USED TO USE
YOU CAN CHANGE THEM WITHOUT ANY ISSUE 
"""
